{
  config,
  lib,
  pkgs,
  ...
}: let
  s = config.scheme;
  vaultRel = lib.removePrefix "${config.home.homeDirectory}/" config.vault.path;
in {
  options.vault = {
    path = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/Documents/notes/general-vault";
      description = "Absolute path to the primary Obsidian vault.";
    };
  };

  config.home.activation.obsidianAccentColor = lib.hm.dag.entryAfter ["writeBoundary"] ''
    appearance="${config.vault.path}/.obsidian/appearance.json"
    if [ -f "$appearance" ]; then
      tmp=$(mktemp)
      ${pkgs.jq}/bin/jq --arg c "#${s.base0F}" '.accentColor = $c' "$appearance" > "$tmp" \
        && $DRY_RUN_CMD mv "$tmp" "$appearance"
    fi
  '';

  config.home.file."${vaultRel}/.obsidian/snippets/base16.css".text = ''
    /* Generated by nix from config.scheme — do not edit.
       Toggle on in Obsidian: Settings → Appearance → CSS snippets → base16. */

    .theme-dark {
      --background-primary:         #${s.base00};
      --background-primary-alt:     #${s.base01};
      --background-secondary:       #${s.base01};
      --background-secondary-alt:   #${s.base02};
      --background-modifier-border: #${s.base02};
      --background-modifier-hover:  #${s.base02};

      --text-normal:   #${s.base05};
      --text-muted:    #${s.base04};
      --text-faint:    #${s.base03};
      --text-accent:   #${s.base0F};
      --text-accent-hover: #${s.base0E};
      --text-on-accent: #${s.base00};
      --text-error:    #${s.base08};
      --text-selection: #${s.base02};

      --interactive-accent:       #${s.base0F};
      --interactive-accent-hover: #${s.base0E};
      --interactive-normal:       #${s.base01};
      --interactive-hover:        #${s.base02};

      --h1-color: #${s.base08};
      --h2-color: #${s.base09};
      --h3-color: #${s.base0A};
      --h4-color: #${s.base0B};
      --h5-color: #${s.base0C};
      --h6-color: #${s.base0D};

      --link-color:           #${s.base0F};
      --link-color-hover:     #${s.base0E};
      --link-unresolved-color: #${s.base08};

      --code-normal:     #${s.base05};
      --code-background: #${s.base01};
      --code-string:     #${s.base0B};
      --code-keyword:    #${s.base0E};
      --code-function:   #${s.base0D};
      --code-comment:    #${s.base03};
      --code-property:   #${s.base0A};
      --code-value:      #${s.base09};
      --code-operator:   #${s.base05};
      --code-tag:        #${s.base08};
      --code-important:  #${s.base09};

      --blockquote-border-color: #${s.base0F};
      --hr-color: #${s.base02};
      --tag-color: #${s.base0C};
      --tag-background: #${s.base01};
      --checkbox-color: #${s.base0B};
      --caret-color: #${s.base05};
    }
  '';
}
